### ISSUE TITLE
[FEATURE] Ingreso de camiones P1

### ISSUE THREAD

**Issue by kteruel** [kteruel/camiones#1]
# Requerimiento Original

Se cargan datos de:
 * Tractor (patente)  se consulta CNRT, si está OK, se graba la información obtenida.
 * Chofer (DNI) se consulta CNRT, si está OK, se gabra la información obtenida.
 * Playo (patente) se consulta CNRT, si está OK, se graba la información obtenida.
 * Contenedor (número) lo cruza con los turnos (agp, terminal) para saber operación y cumplimiento de horario.
 * Alerta de incumplimiento según parámetros
 * Aletra falta de turno
 * Informa terminal

**Comment by kteruel** [comment]
# Análisis Técnico

- Se armará un formulario con los siguientes campos:
  - Patente Tractor
  - DNI Chofer
  - Patente Playo
  - Número Contenedor

## Caso de uso 1
 1a.- El usuario ingresa Patente del Tractor que está llegando a la Terminal. Luego hace click en el botón "Consultar Tractor" 
 1b.- El Sistema encuentra la Patente del Tractor, devuelve los datos y los muestra en pantalla.

## Caso de uso 1.1
 1.1a.- Idem 1a
 1.1b.- El Sistema NO encuentra la Patente del Tractor y muestra en pantalla el mensaje "Tractor no encontrado"

## Caso de uso 2
 2a.- El usuario ingresa DNI de Chofer. Luego hace click en el botón "Consultar Chofer"
 2b.- El Sistema encuentra el Chofer  y muestra los datos en la pantalla.

## Caso de uso 2.1
 2.1a.- Idem 2a
 2.1b.- El Sistema NO encuentra el Chofer y muestra el mensaje "Chofer no encontrado"

## Caso de uso 3
 3a.- El usuario ingresa Patente de PLayo. Luego hace click en el botón "Consultar Playo".
 3b.- El Sistema encuentra el Playo y muestra los datos en pantalla

## Caso de uso 3.1
 3.1a.- Idem 3a.
 3.1b.- El Sistema NO encuentra el Playo y muestra el mensaje "Playo no encontrado".

## Caso de uso 4
 4a.- El usuario ingresa el número del Contenedor. Luego hace click en "Consultar Turno"
 4b.- El Sistema busca el turno y muestra un mensaje de Alerta con color según la comparación del horario actual con el horario del Turno consultado.

## Caso de uso 4.1
 4.1a.- Idem 4a
 4.1b.- El Sistema no encuentra el turno y manda una Alerta de Falta de turno

## Caso de uso 5
 5a.- Una vez que el usuario complete todos los datos del formulario hace click en el botón "Informar Terminal" y envía la información del formulario completo
 5b.- El Sistema guarda la información del formulario en la base de datos con la fecha actual.

**Comment by kteruel** [comment]
# Solicitud de API

Pongo en copia a Diego para la solicitud de API para esté Modulo.

1. Api para consulta de Tractor por medio de la patente
2. Api para consulta de Chofer por medio de DNI
3. Api para consulta de Playo por medio de Patente
4. Api para consulta de Turno por medio de Número de Contenedor
5. Api para envíar información completa del formulario y guardar los datos en la base de datos.

**Comment by kteruel** [comment]
# Consultas

1. ¿Se deberá guardar la información ingresada cada vez que se consulta una entidad? Por ejemplo: Se tiene que guardar en la base de datos la consulta del Tractor, el Chofer, el Playo y el Contenedor cada vez que hace una consulta sobre los mismos.
2. ¿Cuales son los campos a tener en cuenta para solicitar el turno del Tractor?
3. ¿Qué decisiones debo tomar si no encuentro el Tractor/Chofer/Playo? ¿Debo dejar que el usuario siga completando el formulario?

**Comment by reyesdiego** [comment]
1- Se guardará la combinacion Camion, Chofer, Semi, para así la próxima vez ingresar la patente del camion se obtienen los datos y el resto solo hay que chequearlos. No se guarda el contenedor en esa combinacion. En los datos de gate se guarda toda la informacion.
2- El contenedor y/o la patente camion.
3- En caso de no encontrar los datos. Se ingresan y se guarda la combinacion. Por otro lado se indicará que no posee turno pero queda guardada la combinacion.

**Comment by kteruel** [comment]
Muchas gracias por las respuestas a las consultas. 

Para cuando crees que estarían las API para continuar con la programación en función de las Api?

**Comment by reyesdiego** [comment]
Hola Kevin. Hoy estoy reincorporandome, en la semana van a ir saliendo rutas que te voy a ir informando

**Comment by reyesdiego** [comment]
Kevin, en servidor Testing http://190.221.146.245:8090

**1 -** Api para consulta de Turno por Tractor por medio de la Patente
    http://190.221.146.245:8090/zap/turno/patente/<patenteCamion>

     **Ejemplo**
      GET http://190.221.146.245:8090/zap/turno/patente/CAM009
         token: NInijnHJNiuh.....

**1.1-**  Api para consulta de CNRT por Tractor por medio de la Patente  
    http://190.221.146.245:8090/zap/cnrt/patente/<patenteCamion>

     **Ejemplo**
     GET http://190.221.146.245:8090/zap/cnrt/patente/FVO243
     token: NInijnHJNiuh.....

  FVO243 es una patente que está habilitado en CNRT

**2-** Api para consulta de CNRT por Chofer por medio de DNI
    http://190.221.146.245:8090/zap/cnrt/chofer/<DNI>

    **Ejemplo**
    http://190.221.146.245:8090/zap/cnrt/chofer/4159980
    token: NInijnHJNiuh.....

   4159980 es un DNI que está habilitado en CNRT


**4-** Api para consulta de Turno por medio de Número de Contenedor
     GET http://190.221.146.245:8090/zap/turno/contenedor/<contenedor>

  **Ejemplo**
     GET http://190.221.146.245:8090/zap/turno/contenedor/HASU1016369
     token: -r0v7lrrw......


// listado de contenedores con turno activo del dia de hoy ZAP
GET http://190.221.146.245:8090/zap/turnos/contenedores
token: lrrw....

// listado de camiones con turno activo del dia de hoy ZAP
GET http://190.221.146.245:8090/zap/turnos/camiones
token: r0v7lrrw....

**Comment by kteruel** [comment]
Buenísimo! Voy mirando, cualquier cosa te aviso

**Comment by kteruel** [comment]
@reyesdiego de los datos del Tractor, cuales quisieran que muestre en pantalla? 

Los datos que tengo son: 
 * **Dominio**
 * **Año modelo**
 * Empresa Nro
 * Paut
 * País
 * Nro Chasis
 * **Cantidad Ejes**
 * Tipo Vehiculo
 * Chasis Marca
 * Tipo Vehiculo
 * Tipo Carroceria
 * **Razón Social**
 * Tipo Documento
 * Documento

**Comment by kteruel** [comment]
Estos son los datos del Chofer: 

 * **Documento**
 * **Nombre**
 * **Apellido**
 * Fecha Revisión Original
 * Fecha Resolución
 * Categoria
 * Estado

Cuales debería mostrar? 

Otra consulta, que sería la categoría y el estado? En el ejemplo que me pasaste tengo Categoria C y estado R

**Comment by reyesdiego** [comment]
@kteruel Te puse en Bold los que se muestran.
Categoria y Estado no lo vamos a usar, al menos por el momento.

**Comment by reyesdiego** [comment]
### Insertar un Camion en el historico de camiones

POST http://190.221.146.245:8090/zap/camion
Content-Type: application/json
token: gOR1Il1M24klHcq8OqhH1QKxQJvNvsHpNx-r0v7lrrw....
{
"_id": "AS324AA",
"axis": 1,
"year": "2006"
}

### Obtiene un Camion por Patente

GET http://190.221.146.245:8090/zap/camion/AS324AA
token: OR1Il1M24klHcq8OqhH1QKxQJvNvsHpNx-r0v7lrrw...

**Comment by kteruel** [comment]
@reyesdiego no estaría entendiendo como se utiliza el API para insertar un camión en el historico de camiones. 
El _id supongo que sería la patente del camión, pero el axis y el year para que sirven? 
Este Web Service para que pantalla/acción debería usarlo yo?

**Comment by kteruel** [comment]
@reyesdiego consulta, para buscar el Playo por Patente, hay un API? O está pendiente?

**Comment by kteruel** [comment]
@reyesdiego el Web Service para obtener un camión por Patente para que lo estaría necesitando? Además, lo estoy probando y me tira "Not Found"

**Comment by reyesdiego** [comment]
### Insertar un Playo en el historico de Playos

POST http://190.221.146.245:8090/zap/playo
Content-Type: application/json
token: gOR1Il1M24klHcq8OqhH1QKxQJvNvsHpNx-r0v7lrrw....
{
"_id": "ADE100",
"axis": 2,
"year": "1995"
}

Obtiene un Playo por Patente

GET http://190.221.146.245:8090/zap/playo/ADE100
token: OR1Il1M24klHcq8OqhH1QKxQJvNvsHpNx-r0v7lrrw...

**Comment by reyesdiego** [comment]
### Insertar un Historico

POST http://190.221.146.245:8090/zap/historico
Content-Type: application/json
token: gOR1Il1M24klHcq8OqhH1QKxQJvNvsHpNx-r0v7lrrw....
{
    "_id": "NIS628", //patente camion
    "trailerId":  "SET847",
    "driverId": 29753088
}
### Obtiene un Historico por Patente Camion

GET http://190.221.146.245:8090/zap/historico/ADE100
token: OR1Il1M24klHcq8OqhH1QKxQJvNvsHpNx-r0v7lrrw...
