### ISSUE TITLE
API Listado de camiones con turno activo del dia de hoy ZAP

### ISSUE THREAD

**Issue by kteruel** [kteruel/camiones#11]
GET http://190.221.146.245:8090/zap/turnos/camiones
token: r0v7lrrw....

**Comment by kteruel** [comment]
Todavía no salió una respuesta con datos del listado como para saber que variables me retorna. Cuando me devuelva el arreglo con datos programaré el autocomplete de patentes de camiones.

**Comment by reyesdiego** [comment]
Sí, el tema es que desaparecen los camiones del listado a medida que se vencen los turnos, ya que solo muestra los del día. En testing voy agregar mas turnos a futuro para que tengas.
Respuesta ej:

{
  "status": "OK",
  "totalCount": 1,
  "data": [
    "CAM009"
  ]
}

Idem para listado de Contenedores

**Comment by kteruel** [comment]
Con el ejemplo me basta. Ya con eso puedo agregar el autocomplete en la patente del tractor como está en el campo de contenedores. Solamente necesitaba saber como llegaba el dato, por si tenía algo distinto en particular.

**Comment by kteruel** [comment]
@reyesdiego faltaría no mostrar las patentes de los camiones que ya entraron al gate para no mostrarlos en el autocomplete.
