### ISSUE TITLE
API Historico de Playos

### ISSUE THREAD

**Issue by kteruel** [kteruel/camiones#13]
### Insertar un Playo en el historico de Playos

POST http://190.221.146.245:8090/zap/playo
Content-Type: application/json
token: gOR1Il1M24klHcq8OqhH1QKxQJvNvsHpNx-r0v7lrrw....
{
"_id": "ADE100",
"axis": 2,
"year": "1995"
}

Obtiene un Playo por Patente

GET http://190.221.146.245:8090/zap/playo/ADE100
token: OR1Il1M24klHcq8OqhH1QKxQJvNvsHpNx-r0v7lrrw...

**Comment by kteruel** [comment]
@reyesdiego me podrías explicar para que tendría que usar está API? 

Gracias.

**Comment by reyesdiego** [comment]
@kteruel , la idea es guardar los datos del Camion, Playo y Chofer. Luego se guarda la "configuración" o combinación con el API Histórico. El API del Playo en particular es para guardar los datos del playo, como Patente, cantidad de ejes (en otro sistema que hice requerian la cantidad de ejes para identificar en casos de sinistros mas rapido). Puse el "year" pero realmente no lo pidan en pantalla por el momento.

**Comment by kteruel** [comment]
Se modifico el sistema para usar está API antes de consultar al CNRT y dar de alta el Playo en el caso de que no exista en el Historico.
