### ISSUE TITLE
API Historico

### ISSUE THREAD

**Issue by kteruel** [kteruel/camiones#14]
### Insertar un Historico

POST http://190.221.146.245:8090/zap/historico
Content-Type: application/json
token: gOR1Il1M24klHcq8OqhH1QKxQJvNvsHpNx-r0v7lrrw....
{
    "_id": "NIS628", //patente camion
    "trailerId":  "SET847",
    "driverId": 29753088
}
### Obtiene un Historico por Patente Camion

GET http://190.221.146.245:8090/zap/historico/ADE100
token: OR1Il1M24klHcq8OqhH1QKxQJvNvsHpNx-r0v7lrrw...

**Comment by kteruel** [comment]
@reyesdiego no estaría entendiendo para que sirven está API. Podrías explicarmelo? 

Gracias.

**Comment by reyesdiego** [comment]
@kteruel, este API se utiliza en el momento que el usuario ingresa la Patente del Camión. Se le pega al GET y retorna la configuración de la última vez que se registro el camión, es decir, retorna los datos del Camión, del Playo y del Chofer. Con eso cargarías los datos en la pantalla para ser "recheckeados" por el operador. En caso de estar todo OK, se envía nuevamente la configuración con el POST.

**Comment by kteruel** [comment]
@reyesdiego no me estarían funcionando los API's.

El de insertar historico se queda loopeando el request y después me tira un error de time out
El segundo me tira un 404 Not Found

**Comment by reyesdiego** [comment]
@kteruel, estaba faltando subir esto en Testing, perdón. Y a hay FE DE ERRATAS en la descripción del GET que te pasé
La ruta del GET es con "camion"
**GET** http://190.221.146.245:8090/zap/historico/camion/ADE100
token: OR1Il1M24klHcq8OqhH1QKxQJvNvsHpNx-r0v7lrrw...

El GET retorna ej:

{
  "status": "OK",
  "data": {
    "_id": "NIS628",
    "trailerId": {
      "_id": "SET847",
      "axis": 3,
      "year": 1995,
      "__v": 0
    },
    "driverId": {
      "_id": 29753088,
      "lastname": "CELOTTO",
      "firstname": "PAMELA",
      "mobile": "1568735588",
      "__v": 0
    },
    "drivers": [
      23250578,
      29753088
    ],
    "trailers": [
      "SET847"
    ],
    "__v": 2
  }
}
En GET se utiliza driverId y trailerId como el último historico, es lo que se mostraria en pantalla.

**Comment by kteruel** [comment]
Por lo que veo me estaría faltando el dato del tractor (Axis y Año). De igual manera, como no era importante lo vemos mañana si es necesario. Por ahora completo los datos del chofer y del playo cuando hago la consulta al historico.
