### ISSUE TITLE
API Insertar un Chofer

### ISSUE THREAD

**Issue by kteruel** [kteruel/camiones#15]
## Insertar un Chofer
**POST** http://190.221.146.245:8090/zap/chofer
Content-Type: application/json
token: gOR1Il1M24klHcq8OqhH1QKxQJvNvsHpNx-r0v7lrrw....
{
    "_id": 23250578,
    "lastname": "REYES",
    "firstname": "DIEGO",
    "mobile": "15xx73xxxx"
}
## Obtiene un chofer por dni
**GET** http://190.221.146.245:8090/zap/chofer/23250578
token: OR1Il1M24klHcq8OqhH1QKxQJvNvsHpNx-r0v7lrrw...

**Comment by kteruel** [comment]
Reabro la issue porque recordé que la API tenía algo para corregir. 

Actualmente, cuando se consulta un chofer por dni en está API te devuelve error 500 aunque encuentre o no encuentre un chofer.

Lo ideal es que devuelva un 200 cuando lo encuentra o un 400 si no lo encuentra.

**Comment by reyesdiego** [comment]
@kteruel, error de copiar y pegar linea. Va a retornar 500 con algún error del servidor, en caso de no encontrar al Chofer retorna 200 con un array vacío. El 400 gralmente lo uso por si hay algún error en el payload desde el cliente.
