### ISSUE TITLE
API - Consultar Patente de Playo en CNRT

### ISSUE THREAD

**Issue by kteruel** [kteruel/camiones#16]
Api para consultar la existencia de un Playo en el CNRT por medio de Patente. 

Se utilizará para la Pantalla de Ingreso de Camiones en el campo Patente de Playo

**Comment by reyesdiego** [comment]
GET http://190.221.146.245:8090/zap/cnrt/patente/playo/FVO243
token: JvNvsHpNx-r0v7lrrw

Este ej. retorna los datos de un camión, no encontré datos que sean de un trailer por lo tanto no tengo claro que retorna el API, estimamos que lo mismo.
