### ISSUE TITLE
API-Registro Entrada y/o Salida de Camiones

### ISSUE THREAD

**Issue by reyesdiego** [kteruel/camiones#17]
### Registro de Horario de Entrada de Camión
**POST** http://190.221.146.245:8080/gate
Content-Type: application/json
token: OqhH1QKxQJvNvsHpNx-r0v7lrrw...

{ 
    "mov": "IMPO", 
    "tipo": "IN", 
    "carga": "LL", 
    "patenteCamion": "WWW333", 
    "gateTimestamp":"2017-11-24T07:00:00.000Z"
}

### Registro de Horario de Salida de Camión
**POST** http://190.221.146.245:8080/gate
Content-Type: application/json
token: v7lrrw...

{ 
    "mov": "IMPO", 
    "tipo": "OUT", 
    "carga": "LL", 
    "patenteCamion": "WWW333", 
    "gateTimestamp":"2017-11-24T08:00:00.000Z"
}

**-- Notar que el PORT es 8080 --**

A tener en cuenta, los tipos de movimientos "mov" posibles son "IMPO" y "EXPO". En gral. los camiones de IMPO no tendran contenedor y los de EXPO sí. En la propiedad "carga" se registra el tipo de carga a saber, "LL" con Contenedor lleno, "VA" con Contenedor Vacio (para cuando registremos también camiones que vienen a devolver contenedores a la terminal) y "NO" cuando el Camión no lleva Contenedor en el playo.

Estas 2 rutas registran el Horario de entrada y salida del camión.

Se verificará la patente del camión en cuanto a consistencia en el formato. Si bien no se podrá verificar que la patente ingresada pertenezca a un camión al menos se chequeará que el formato sea válido para no registrar "XXXXXX" por ej. Por el momento no se puede validar cuando envíen "AAA111" si pertenece o no a un camión

**Comment by kteruel** [comment]
@reyesdiego una consulta, el mov y la carga de donde saco la información? Porque del turno solamente tengo la información de mov pero no tengo carga en ningún lugar. Debería preguntarle al usuario esa información? Y en caso de que se le pregunte, también debería preguntarle también el Movimiento?

**Comment by reyesdiego** [comment]
@kteruel, la "Carga" en el Turno no se guarda, en las terminales no tienen esa información, ellos toman turnos para Importación, Exportación y Devolución o Retiro de Contenedores Vacios. En el Gate se guarda la Carga porque por dos razones, es ahí donde realmente sabes como pasó el camión y segundo que pueden haber gates que no tuvieron turno y no se podria relacionar la "carga"

**Comment by kteruel** [comment]
Okey, entonces debería agregar un campo en el formulario de ingreso de Camión para saber que tipo de Carga estamos teniendo. Es cierto? 
Y con el Movimiento, lo saco del Turno? O también lo pregunto en el formulario?

**Comment by kteruel** [comment]
@reyesdiego con respecto a está API de entrada de camiones. No estaría entendiendo como le informo al API cual es el turno seleccionado como para que se lo guarde en la base de datos y después lo tengamos para mostrar en el listado de camiones en gate como para mostrar las diferencias de horarios y los colores.

**Comment by kteruel** [comment]
@reyesdiego ayer estaba viendo el tema del gate out en la pantalla de salida. Pero me quedo una consulta que no te la pase. 
Ahí en los parametros me estás diciendo que tengo que pasar la carga y el movimiento. Pero tengo entendido que solamente se pedía la patente del Tractor para hacer una salida. O tengo que actualizar el formulario para agregar esos dos campos?
