### ISSUE TITLE
API - Listado de camiones en gate

### ISSUE THREAD

**Issue by kteruel** [kteruel/camiones#18]
Necesitaría tener un API donde me muestre los camiones que tengo en gate como para mostrarlos en el Administrador de Playo.

Esto debería devolver la información de Camión/Chofer/Patente + Turno seleccionado en el Ingreso de Camiones + Fecha y Hora de ingreso de Camión.

Necesitaría tener los dos campos de fechas para saber que configuración de colores tengo que mostrar según la diferencia de tiempo entre el turno y el ingreso del camión.

**Comment by reyesdiego** [comment]
### Camiones en Playa (Listado de Gates con sus respectivas entradas y salidas
GET http://190.221.146.245:8090/gates/ZAP/0/10000?fechaInicio=2017-11-24T00:00:00.000-03:00&fechaFin=2017-11-25T00:00:00.000-03:00
token: .gOR1Il1M24klHcq8OqhH1QKxQJvNvsHpNx-r0v7lrrw.....

Result sample
{
  "status": "OK",
  "totalCount": 2,
  "pageCount": 2,
  "data": [
    {
      "_id": 10419269,
      "terminal": "ZAP",
      "contenedor": null,
      "buque": null,
      "viaje": null,
      "gateTimestamp": "2017-11-24T07:00:00.000Z",
      "gateTimestamp_in": "2017-11-24T07:00:00.000Z",
      "gateTimestamp_out": "2017-11-24T08:00:00.000Z",
      "timeInside": "1:00 hs.",
      "turnoInicio": "2017-11-29T13:26:52.000Z",
      "turnoFin": "2017-11-29T13:26:52.000Z",
      "carga": "LL",
      "tipo": "IN",
      "mov": "IMPO",
      "patenteCamion": "WWW333",
      "tren": null,
      "largo": null
    },
    {
      "_id": 10419271,
      "terminal": "ZAP",
      "contenedor": null,
      "buque": null,
      "viaje": null,
      "gateTimestamp": "2017-11-24T08:00:00.000Z",
      "gateTimestamp_in": "2017-11-24T07:00:00.000Z",
      "gateTimestamp_out": "2017-11-24T08:00:00.000Z",
      "timeInside": "1:00 hs.",
      "turnoInicio": "2017-11-29T13:36:17.000Z",
      "turnoFin": "2017-11-29T13:36:17.000Z",
      "carga": "LL",
      "tipo": "OUT",
      "mov": "IMPO",
      "patenteCamion": "WWW333",
      "tren": null,
      "largo": null
    }
  ],
  "time": 200
}
