### ISSUE TITLE
Datos del Turno encontrado

### ISSUE THREAD

**Issue by reyesdiego** [kteruel/camiones#22]
Si encuentra el turno, donde se muestra el "Movimiento" siendo este IMPO EXPO, etc, esto datos provenientes del turno hay que agregar en pantalla dos datos mas, "alta", que es la fecha en que se dio de alta el turno y "terminal" hacia donde se dirije el camión.

**Comment by reyesdiego** [comment]
@kteruel . Originalmente el issue pide mostrar en pantalla los datos de "fecha de alta" y "terminal". Estan resueltos como hidden. Deben mostrarse en pantalla. El campo "terminal" retornara "BACTSSA", "TRP" o "TERMINAL4". 
Fe De Erratas; El Campo "Fecha de Alta" pedido originalemente no se va a mostrar.
Pero sí fundamental que si el turno buscado al buscar por patente (al inicio de la pantalla) retorna un turno, Mostrar en el campo contenedor el contenedor que devuelva el mismo.

**Comment by kteruel** [comment]
@reyesdiego el campo terminal se puede editar? O es solamente visible?

**Comment by kteruel** [comment]
Hola @reyesdiego, estuve haciendo las modificaciones pero me encontré con una diferencia... En un principio cuando yo consultaba el turno por Patente o por Contenedor me devolvía el mismo json con la misma información. 

Pero ahora me devuelve estos dos json: 

 - Consulta de turnos por Patente: 
```
{
    "status": "OK",
    "data": [
        {
            "contenedor": "SLSU8039988",
            "inicio": "2017-12-04T13:00:00.000Z",
            "fin": "2017-12-04T13:55:00.000Z",
            "transporte": {
                "camion": "CAM009",
                "dni": 23250578,
                "celular": 1545670890
            }
        }
    ]
}
```

 - Consulta de Turnos por Contenedor
```
{
    "status": "OK",
    "data": [
        {
            "_id": "5a0f0339c2fe679876a2c20d",
            "buque": "SSOU",
            "viaje": "SSOU624",
            "contenedor": "SLSU8039988",
            "inicio": "2017-12-04T13:00:00.000Z",
            "fin": "2017-12-04T13:55:00.000Z",
            "mov": "IMPO",
            "alta": "2017-11-17T15:41:45.237Z",
            "user": "TERMINAL",
            "disponibles_t1": 0,
            "email": "mariano.steininger@trp.com.ar",
            "verifica": "2017-12-07T03:00:00.000Z",
            "verifica_turno": "MA",
            "verifica_tipo": "PISO",
            "terminal": "TRP",
            "__v": 0,
            "hold": {
                "date": "2017-10-24T01:23:18.847Z",
                "status": true
            },
            "transporte": {
                "camion": "CAM009",
                "semi": "DDS971",
                "dni": 23250578,
                "celular": 1545670890,
                "date": "2017-12-01T18:48:37.853Z"
            }
        }
    ]
}
```

Necesitaría saber si es correcto lo que devuelven ahora porque tendría que tocar el Sistema para que dependendiendo de donde consulta el turno estaría reaccionando de diferentes maneras. 

Confirmame si es correcto como devuelven los json y estaría trabajando para arreglarlo.

**Comment by reyesdiego** [comment]
@kteruel , es la misma respuesta pero resumida cuando es por patente ya que no se muestra mas que eso. Lo unico que debo agregar es la Terminal en "por patente" ya que antes no se mostraba la misma y agregaré el _id que es útil y lo omití. Pero no debes tocar nada para que reaccione diferente.

**Comment by kteruel** [comment]
Si, por eso, como era diferente habían campos que no se estaban completando. También el que tenes que agregar es "mov" porque también si se consulta por patente no va a completar ese dato.

Entonces el issue está **Resuelto** ya que completa los datos correctamente a partir de la información recibida.

**Comment by kteruel** [comment]
@reyesdiego esté issue se puede cerrar ? O falta algo para hacer?
