### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by reyesdiego** [kteruel/camiones#23]
Verificar porque aparentemente se cuelga luego de internar hacer login con un usuario o clave incorrecta.

**Comment by kteruel** [comment]
@reyesdiego en mi máquina local está funcionando bien. 

Para resolverlo en el servidor necesitaria que reproduzcas el error y me pases las últimas lineas de los siguientes logs: 

/var/www/camiones/var/logs/prod.log
/var/logs/apache2/error.log

Posiblemente el error esté en el primer log, así que si tenes ese nada más está bien. 

Aguardo tu respuesta.

Saludos!
