### ISSUE TITLE
[FEATURE] Salida de camiones

### ISSUE THREAD

**Issue by kteruel** [kteruel/camiones#3]
# Requerimiento Original

 * Sobre los camiones ingresados, registro el egreso.
 * Informo terminal

**Comment by kteruel** [comment]
# Análisis Técnico

- Se mostrará un formulario con los siguientes campos:
  - Patente de Tractor

## Caso de uso 1
1a. El usuario ingresa la patente del tractor y hace click en el botón "Registrar Salida"
1b. El sistema busca el tractor en la base de datos y registra la fecha y hora de salida.

**Comment by kteruel** [comment]
# API

1. Api para ingresar la fecha de egreso en la base de datos a partir de patente de Tractor

**Comment by kteruel** [comment]
# Consulta

1. ¿Cuales son los campos que tengo que ingresar para registrar una salida de camión? ¿Es correcto que con la patente puedo registrarlo, o necesito más información?

**Comment by reyesdiego** [comment]
1- Solo informar la patente,  fecha y hora para buscar el ingreso y guardar la salida sobre ese ingreso.

**Comment by kteruel** [comment]
Muchas gracias por las respuestas a las consultas. 

Para cuando crees que estaría la API para continuar con la programación en función de la Api?
