### ISSUE TITLE
[FEATURE] Administración de playa (colas y estacionados)

### ISSUE THREAD

**Issue by kteruel** [kteruel/camiones#4]
# Requerimiento Original

* Camiones en ZAP por terminal, operatoria, turno y orden de arribo
* Navegable para más info
* Colores por alertas
* Camiones sin turno o alertados por horario
* Gestiona turnos con terminal

**Comment by kteruel** [comment]
# Análisis Técnico

- Se mostrará un listado de camiones con las siguientes columnas
  - Patente
  - Terminal
  - Operatoria
  - Turno
  - Orden de arribo
- El listado se podrá ordenar por cualquier columna
- Cada columna tendrá un campo para poder filtrar la información del listado.
- Por cada fila del listado se ingresará un botón "Ver" para ver más información del Camión en la playa. También se agregará un botón que emitirá la salida del camión.
- Las filas de los camiones tendrán los siguientes colores
  - Rojo: Llego muy tarde
  - Naranja: Llego tarde
  - Amarillo: Llego antes de tiempo
  - Verde: Llego a tiempo
- El rango de tiempo de cada color será configurado dentro del Sistema. Accesible para configurar en el momento de la implementación del Sistema.
- Los camiones que no tengan turno se mostrarán con color gris para identificarlos fácilmente. Al final de la fila se agregará un botón para consultar nuevamente si ya se ingreso un turno para ese camión.

**Comment by kteruel** [comment]
# Consultas

1. ¿Qué es el campo "Operatoria"?
2. ¿Qué es el campo "Orden de arribo"?

**Comment by kteruel** [comment]
# API

1. Api de listado de camiones en playa
2. Api para consultar más información del Camión en la playa.
3. Api para consultar si el camión ya solicito un turno.

**Comment by reyesdiego** [comment]
1- Operatoria es el tipo de movimiento, importación, exportación, vacios: IMPO EXPO VACIO.
2 - Es un dato de la terminal con las agencias, no recuerdo ahora porque se nombra en este esquema, consulto y te aviso.

**Comment by kteruel** [comment]
Perfecto, aguardo la respuesta sobre Orden de arribo. 

¿Para cuando crees que van a estar las Api para continuar con la funcionalidad en relación con las Api?
