### ISSUE TITLE
[FEATURE] Alta Chofer en Ingreso de Camiones

### ISSUE THREAD

**Issue by kteruel** [kteruel/camiones#5]
# Historia

Como Usuario quiero poder dar de alta un Chofer en el caso de que no lo encuentre en mi Base de Datos.

## Análisis Técnico
 * Se deberá mostrar un modal con el mensaje "No se encontró Chofer. Por favor, completar los datos" que tenga los siguientes datos: 
    * Nombre
    * Apellido
    * Teléfono
 * Deberá haber un botón para dar de alta ("Guardar"). Que disparará un Web Services donde guarda los datos del Chofer y cierra el modal.
 * Se deberá completar los datos del Chofer como si estuviera existiendo en la Base de datos.

## Solicitud de API
 * Api para dar de alta un Chofer en el Sistema con los parametros mencionados anteriormente

**Comment by reyesdiego** [comment]
## Insertar un Chofer
**POST** http://190.221.146.245:8090/zap/chofer
Content-Type: application/json
token: gOR1Il1M24klHcq8OqhH1QKxQJvNvsHpNx-r0v7lrrw....
{
    "_id": 23250578,
    "lastname": "REYES",
    "firstname": "DIEGO",
    "mobile": "15xx73xxxx"
}
## Obtiene un chofer por dni
**GET** http://190.221.146.245:8090/zap/chofer/23250578
token: OR1Il1M24klHcq8OqhH1QKxQJvNvsHpNx-r0v7lrrw...

**Comment by kteruel** [comment]
@reyesdiego una consulta, en los parametros está el _id que tengo que ingresar para dar de alta un chofer. Probé con usar los 3 parametros menos el id y me tiro el siguiente error

```
document must have an _id before saving
```

Como me estaría dando cuenta cual es el id que tengo que ingresar? No debería ser autogenerado por la base de datos y que yo solamente ingrese los datos del chofer?

**Comment by kteruel** [comment]
@reyesdiego 

El Web Service de alta Chofer funciona bien.

Lo que sí, el Web Service de consulta devuelve un Status 500 cuando encuentra el Chofer. Se podría cambiar a Status 200? 

Muchas gracias

**Comment by kteruel** [comment]
Agrego el caso de Uso para tener en claro el flujo de ingreso de chofer

# Caso de Uso
1.- El Usuario Ingresa el Documento del Chofer en el Sistema
2.- El Sistema encuentra el Documento del Chofer en el ZAP y completa los datos
3.- El Sistema encuentra el Documento del Chofer en el CNRT y completa los datos

2.1.- El Sistema no encuentra el Documento del Chofer en el ZAP
2.2.- El Sistema abre un Formulario para completar los datos del Chofer
2.3.- El Usuario completa los datos del Chofer en el formulario y los guarda
2.4.- El Sistema guarda los datos del Chofer en el ZAP
2.5.- Vuelve al paso número 3

3.1.- El Sistema no encuentra los datos del Chofer en el CNRT
3.2.- El Sistema muestra en pantalla el mensaje "No se encontraron los datos del Chofer en el CNRT"
